[package]
name = "RustyWorkflow"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Walczak <01.piotrwalczak@gmail.com>"]

[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }
tonic = "0.11.0"
prost = "0.12.3"

[build-dependencies]
tonic-build = "0.11.0"