[package]
name = "wgvideo"
version = "0.1.0"
edition = "2021"
authors = ["Piotr Walczak <01.piotrwalczak@gmail.com>"]

[dependencies]
axum = "0.7.4"
tokio = { version = "1.36.0", features = ["full"] }